scss_files: 'src/static/styles/**/*.scss'
exclude: 'src/static/styles/vendor/**'

linters:
    Indentation:
        width: 4
    ColorVariable:
        enabled: false
    IdSelector:
        enabled: false
    ColorKeyword:
        enabled: false
    SelectorDepth:
        max_depth: 4
    PropertySortOrder:
        enabled: false
    PseudoElement:
        enabled: false
