scss_files: 'src/static/styles/**/*.scss'
exclude: 'src/static/styles/vendor/**'

linters:
    Indentation:
        width: 4
    ColorVariable:
        enabled: false
    IdSelector:
        enabled: false
    ColorKeyword:
        enabled: false
    SelectorDepth:
        max_depth: 8
    PropertySortOrder:
        enabled: false
    PseudoElement:
        enabled: false
    MergeableSelector:
        enabled: false
    QualifyingElement:
        enabled: false

# SCSS specific stuff
    NestingDepth:
        max_depth: 6
    PlaceholderInExtend:
        enabled: false
